# Generated by Django 5.2.7 on 2025-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'MEMBER'), ('A', 'ADMIN'), ('C', 'COACH')], default='M', max_length=1),
        ),
    ]
