# Generated by Django 5.2.7 on 2025-11-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_activation_code_user_activation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
